all:
	g++ -O3 -g3 -march=skylake -o compiled/cpu_sum ./cpu_sum.cpp
	g++ -O3 -g3 -march=skylake -o compiled/cpu_min ./cpu_min.cpp
	g++ -O3 -g3 -march=skylake -o compiled/cpu_integral_image ./cpu_integral_image.cpp
